remote_theme: "mmistakes/minimal-mistakes@4.22.0"
#remote_theme: minimal-mistakes-jekyll
title: VocabulariosFEMP
layout: single
plugins:
  - jekyll-include-cache  
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
      
sidebar:
  nav: "docs"
